version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.2
    working_directory: /go/src/github.com/tdrk18-private/nlp100-golang
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: |
            make install-lint
      - run:
          name: Run golangci-lint
          command: |
            make lint
      - run:
          name: Run test
          command: |
            make test
